[32mINFO[0m:     [14-10-2024 10:22:56] Set chroma_server_nofile to 65535
[32mINFO[0m:     [14-10-2024 10:22:56] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [14-10-2024 10:22:56] Starting component System
[36mDEBUG[0m:    [14-10-2024 10:22:56] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [14-10-2024 10:22:56] Starting component SqliteDB
[36mDEBUG[0m:    [14-10-2024 10:22:57] Starting component QuotaEnforcer
[36mDEBUG[0m:    [14-10-2024 10:22:57] Starting component Posthog
[36mDEBUG[0m:    [14-10-2024 10:22:57] Starting component LocalSegmentManager
[36mDEBUG[0m:    [14-10-2024 10:22:57] Starting component SegmentAPI
[32mINFO[0m:     [14-10-2024 10:22:57] Started server process [[36m103715[0m]
[32mINFO[0m:     [14-10-2024 10:22:57] Waiting for application startup.
[32mINFO[0m:     [14-10-2024 10:22:57] Application startup complete.
[32mINFO[0m:     [14-10-2024 10:22:57] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [14-10-2024 10:23:07] ::1:53248 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:23:42] ::1:33984 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:24:24] ::1:48832 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:25:13] ::1:56614 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:26:01] ::1:47974 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:26:13] ::1:47962 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:26:32] ::1:48060 - "GET /api/v1/tenants/multimodal_chatbot HTTP/1.1" 404
[32mINFO[0m:     [14-10-2024 10:27:01] Shutting down
[32mINFO[0m:     [14-10-2024 10:27:01] Waiting for application shutdown.
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component System
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component SegmentAPI
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component Posthog
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component SqliteDB
[36mDEBUG[0m:    [14-10-2024 10:27:01] Stopping component OpenTelemetryClient
[32mINFO[0m:     [14-10-2024 10:27:01] Application shutdown complete.
[32mINFO[0m:     [14-10-2024 10:27:01] Finished server process [[36m103715[0m]
[32mINFO[0m:     [14-10-2024 10:29:46] Set chroma_server_nofile to 65535
[32mINFO[0m:     [14-10-2024 10:29:46] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component System
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component SqliteDB
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component QuotaEnforcer
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component Posthog
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component LocalSegmentManager
[36mDEBUG[0m:    [14-10-2024 10:29:46] Starting component SegmentAPI
[32mINFO[0m:     [14-10-2024 10:29:47] Started server process [[36m110836[0m]
[32mINFO[0m:     [14-10-2024 10:29:47] Waiting for application startup.
[32mINFO[0m:     [14-10-2024 10:29:47] Application startup complete.
[32mINFO[0m:     [14-10-2024 10:29:47] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [14-10-2024 10:29:52] ::1:46476 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:29:52] ::1:46476 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:29:52] ::1:46476 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:29:52] ::1:46476 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:31:06] ::1:34226 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:31:06] ::1:34226 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:31:06] ::1:34226 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [14-10-2024 10:31:06] Collection multimodal_chatbot already exists
Traceback (most recent call last):
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 111, in receive
    return self.receive_nowait()
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 157, in call_next
    message = await recv_stream.receive()
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 98, in catch_exceptions_middleware
    return await call_next(request)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 112, in check_http_version_middleware
    return await call_next(request)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 640, in create_collection
    await to_thread.run_sync(
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2357, in run_sync_in_worker_thread
    return await future
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 629, in process_create_collection
    return self._api.create_collection(
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/api/segment.py", line 176, in create_collection
    coll, created = self._sysdb.create_collection(
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "/home/ranker/Desktop/Gen-AI/venv/lib/python3.10/site-packages/chromadb/db/mixins/sysdb.py", line 233, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection multimodal_chatbot already exists
[32mINFO[0m:     [14-10-2024 10:31:06] ::1:34226 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [14-10-2024 10:31:06] ::1:34226 - "GET /api/v1/collections/multimodal_chatbot?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [14-10-2024 10:57:21] Shutting down
[32mINFO[0m:     [14-10-2024 10:57:21] Waiting for application shutdown.
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component System
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component SegmentAPI
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component Posthog
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component SqliteDB
[36mDEBUG[0m:    [14-10-2024 10:57:21] Stopping component OpenTelemetryClient
[32mINFO[0m:     [14-10-2024 10:57:21] Application shutdown complete.
[32mINFO[0m:     [14-10-2024 10:57:21] Finished server process [[36m110836[0m]
